### ISSUE TITLE
WFN freezes the computer

### ISSUE THREAD

**Issue by andradadad** [wokhan/WFN#154]
I've tried this software for so many times over the years. It always freezes my computer to the point of having to switch the energy plug off.
Nightly x64 8gbRAM 1gb vram windows 7 .Net 4.8-4.0.  I've opened WFN, and it shows RAM at 99% and CPU at 40%~ freezing windows. 

I've tried 'silent block' to see if it was the prompts, but by clicking to launch the notifier, it freezes. I have to wait several minutes to see it didn't block anything. I'm tired of having to switch the plug off or waiting the computer to respond idle, to check finally if outbound would block anything.

Just a feedback that I tried but couldn't use this software which seems to me an essential tool.

**Comment by wokhan** [comment]
Hi,
Thanks for your feedback, I appreciate that you took the time to comment while clearly it doesn't work as expected for you :-)
I'm pretty surprised that you still have issues even with the nightly since it contains manyyyy fixes and improvements.
Could you please enable the debug log (through the options) and check if anything seems off in there?
Thank you again!

**Comment by wokhan** [comment]
I picked the wrong issue number in the previous commit mentioned above. It was for #159 , sorry about that.
Btw I'm closing this issue as I didn't get any feedback since last time (I hope I didn't kill you internet @andradadad 🤣 I'm joking of course). Feel free to tell if you still have issues.
