### ISSUE TITLE
Firewall rules screen is empty [bug]

### ISSUE THREAD

**Issue by selivan** [wokhan/WFN#156]
WFN version: 2.5 Beta
Windows version: 11 22H2
![image](https://user-images.githubusercontent.com/1208989/224337772-a452215b-ac28-48ee-924a-6008ee48efe7.png)

**Comment by wokhan** [comment]
Hi, this is fun because even if I developed this software I sometimes react as you do regarding this screen. In fact the WFN-created rules are shown by default... which means none will be displayed if you didn't create any. I agree it doesnt make sense, I'll change the default option to show all rules at first.
Adding this to the backlog.
Thanks

**Comment by selivan** [comment]
In latest nightly ( wfn-20230312-c0ea1e-x64-standalone.zip ) all rules are shown.
